
CREATE SCHEMA call_center;
USE call_center;

-- CREAR LAS TABLAS

CREATE TABLE CLIENTES(
	ID_CLIENTE INT,
    NOMBRE VARCHAR(50),
    CREATED_AT INT
);

CREATE TABLE CAMPANIAS(
	ID_CAMPANIA INT,
    ID_CLIENTE INT,
    NOMBRE VARCHAR(50)
);

CREATE TABLE EMPLEADOS(
	LEGAJO INT,
    ID_DEPARTAMENTO INT,
    ID_PUESTO INT,
    ID_CAMPANIA INT,
    NOMBRE VARCHAR(30),
    APELLIDO VARCHAR(30),
    EMAIL VARCHAR(40),
    USUARIO VARCHAR(15),
    PASS VARCHAR(65),
    FECHA_INGRESO DATE,
    FECHA_EGRESO DATE,
    MOTIVO_EGRESO VARCHAR(60)
);

CREATE TABLE ASIGNACION_EMPLEADOS_CAMPANIAS(
	ID_ASIGNACION INT,
    LEGAJO INT,
    ID_CAMPANIA INT
);

CREATE TABLE PUESTOS(
	ID_PUESTO INT,
    ID_DEPARTAMENTO INT,
    NOMBRE VARCHAR(30),
    DESCRIPCION VARCHAR(50)
);

CREATE TABLE DEPARTAMENTOS(
	ID_DEPARTAMENTO INT,
    NOMBRE VARCHAR(30)
);

CREATE TABLE EVENTOS(
	ID_EVENTO INT,
    NOMBRE VARCHAR(50),
    TIPO_EVENTO VARCHAR(20)
);

CREATE TABLE VENTAS(
	ID_VENTA INT,
    ID_CAMPANIA INT,
    LEGAJO INT,
    FECHA DATE
);

-- AGREGAR PK Y FK

ALTER TABLE CLIENTES
CHANGE COLUMN ID_CLIENTE ID_CLIENTE INT NOT NULL AUTO_INCREMENT,
ADD PRIMARY KEY (ID_CLIENTE);

ALTER TABLE CAMPANIAS
CHANGE COLUMN ID_CAMPANIA ID_CAMPANIA INT NOT NULL AUTO_INCREMENT,
ADD PRIMARY KEY (ID_CAMPANIA);

ALTER TABLE EMPLEADOS
CHANGE COLUMN LEGAJO LEGAJO INT NOT NULL,
ADD PRIMARY KEY (LEGAJO);

ALTER TABLE ASIGNACION_EMPLEADOS_CAMPANIAS
CHANGE COLUMN ID_ASIGNACION ID_ASIGNACION INT NOT NULL AUTO_INCREMENT,
ADD PRIMARY KEY (ID_ASIGNACION);

ALTER TABLE PUESTOS
CHANGE COLUMN ID_PUESTO ID_PUESTO INT NOT NULL AUTO_INCREMENT,
ADD PRIMARY KEY (ID_PUESTO);

ALTER TABLE DEPARTAMENTOS
CHANGE COLUMN ID_DEPARTAMENTO ID_DEPARTAMENTO INT NOT NULL AUTO_INCREMENT,
ADD PRIMARY KEY (ID_DEPARTAMENTO);

ALTER TABLE EVENTOS
CHANGE COLUMN ID_EVENTO ID_EVENTO INT NOT NULL AUTO_INCREMENT,
ADD PRIMARY KEY (ID_EVENTO);

ALTER TABLE VENTAS
CHANGE COLUMN ID_VENTA ID_VENTA INT NOT NULL AUTO_INCREMENT,
ADD PRIMARY KEY (ID_VENTA);

ALTER TABLE CAMPANIAS
ADD FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE);

ALTER TABLE EMPLEADOS
ADD FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTOS(ID_DEPARTAMENTO),
ADD FOREIGN KEY (ID_PUESTO) REFERENCES PUESTOS(ID_PUESTO),
ADD FOREIGN KEY (ID_CAMPANIA) REFERENCES CAMPANIAS(ID_CAMPANIA);

ALTER TABLE ASIGNACION_EMPLEADOS_CAMPANIAS
ADD FOREIGN KEY (LEGAJO) REFERENCES EMPLEADOS(LEGAJO),
ADD FOREIGN KEY (ID_CAMPANIA) REFERENCES CAMPANIAS(ID_CAMPANIA);

ALTER TABLE PUESTOS
ADD FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTOS(ID_DEPARTAMENTO);

ALTER TABLE VENTAS
ADD FOREIGN KEY (ID_CAMPANIA) REFERENCES CAMPANIAS(ID_CAMPANIA),
ADD FOREIGN KEY (LEGAJO) REFERENCES EMPLEADOS(LEGAJO);


